pathrouter:
  image: foodpedia/pathrouter
  ports:
    - "80:80"
  links:
    - endpoint
    - pubby
    - home
    - ontologies
    - ldf
  restart: always

home:
  image: foodpedia/home_production
  restart: always

pubby:
  image: foodpedia/pubby
  links:
    - endpoint
  command: http://foodpedia.tk http://endpoint:8890/sparql
  restart: always

endpoint:
  image: foodpedia/virtuoso_ontowiki
  volumes:
    - ./upload:/upload
  restart: always

ldf:
  image: foodpedia/foodpedia-ldf
  restart: always

foodontologyupdater:
  build: food-ontology-updater
  ports:
    - "8008:80"
  volumes:
    - ~/.ssh:/root/.ssh
  restart: always

ontologies:
  image: foodpedia/ontologies
  ports:
    - "8080:80"
  restart: always
